import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef } from 'react';
import { estimateMessageHeight } from './messageHeightEstimate';
import type { MessageWindowingContextValue, PinReason, RowRegistration, RowToken } from './types';
export const OVERSCAN_PX = 1200;
export const UNMOUNT_HYSTERESIS_PX = 2400;
type Row = RowRegistration & { mounted: boolean; height: number; pins: Set<PinReason>; waiters: Array<(el: HTMLElement | null) => void> };
const Context = createContext<MessageWindowingContextValue | null>(null);
export function MessageWindowingProvider({ children, scrollableRef, conversationId }: { children: React.ReactNode; scrollableRef: React.RefObject<HTMLElement>; conversationId?: string | null }) {
  const rows = useRef(new Map<RowToken, Row>()), byId = useRef(new Map<string, Row>()), frame = useRef<number>(), materialized = useRef(false), observer = useRef<IntersectionObserver>(), resize = useRef<ResizeObserver>();
  const setMounted = useCallback((row: Row, value: boolean) => { if (row.mounted === value) return; row.mounted = value; row.setMounted(value); if (value) row.waiters.splice(0).forEach((resolve) => resolve(row.element)); }, []);
  const evaluate = useCallback(() => { const root = scrollableRef.current ?? document.querySelector<HTMLElement>('.scrollbar-gutter-stable'); if (!root) return; const bounds = root.getBoundingClientRect(); rows.current.forEach((row) => { if (!row.element || materialized.current || row.forceMounted || row.pins.size) return setMounted(row, true); const box = row.element.getBoundingClientRect(); const near = box.bottom >= bounds.top - OVERSCAN_PX && box.top <= bounds.bottom + OVERSCAN_PX; const far = box.bottom < bounds.top - UNMOUNT_HYSTERESIS_PX || box.top > bounds.bottom + UNMOUNT_HYSTERESIS_PX; if (near) setMounted(row, true); else if (far) setMounted(row, false); }); }, [scrollableRef, setMounted]);
  const schedule = useCallback(() => { if (frame.current != null) return; frame.current = requestAnimationFrame(() => { frame.current = undefined; evaluate(); }); }, [evaluate]);
  const registerRow = useCallback((registration: RowRegistration) => { const row: Row = { ...registration, mounted: true, height: estimateMessageHeight(registration.message), pins: new Set(), waiters: [] }; rows.current.set(registration.token, row); byId.current.set(registration.id, row); if (observer.current && registration.element) observer.current.observe(registration.element); if (resize.current && registration.element) resize.current.observe(registration.element); schedule(); return () => { if (registration.element) { observer.current?.unobserve(registration.element); resize.current?.unobserve(registration.element); } rows.current.delete(registration.token); if (byId.current.get(registration.id) === row) byId.current.delete(registration.id); row.waiters.splice(0).forEach((resolve) => resolve(null)); }; }, [schedule]);
  const updateRowId = useCallback((token: RowToken, oldId: string, newId: string) => { const row = rows.current.get(token); if (!row) return; if (byId.current.get(oldId) === row) byId.current.delete(oldId); row.id = newId; byId.current.set(newId, row); }, []);
  const reportHeight = useCallback((token: RowToken, height: number) => { const row = rows.current.get(token); if (row && height > 0) row.height = Math.round(height * 10) / 10; }, []);
  const isMounted = useCallback((token: RowToken) => rows.current.get(token)?.mounted ?? false, []);
  const pinRow = useCallback((token: RowToken, reason: PinReason) => { const row = rows.current.get(token); if (!row) return () => {}; row.pins.add(reason); setMounted(row, true); return () => { row.pins.delete(reason); schedule(); }; }, [schedule, setMounted]);
  const ensureMessageMounted = useCallback(async (id: string) => { const row = byId.current.get(id); if (!row) return null; setMounted(row, true); return row.element ?? new Promise<HTMLElement | null>((resolve) => row.waiters.push(resolve)); }, [setMounted]);
  const materializeAll = useCallback(async (_reason: 'screenshot' | 'find' | 'debug') => { materialized.current = true; rows.current.forEach((row) => setMounted(row, true)); await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))); return () => { materialized.current = false; schedule(); }; }, [schedule, setMounted]);
  const value = useMemo(() => ({ registerRow, updateRowId, reportHeight, isMounted, pinRow, ensureMessageMounted, materializeAll, notifyLayoutChange: schedule }), [registerRow, updateRowId, reportHeight, isMounted, pinRow, ensureMessageMounted, materializeAll, schedule]);
  useEffect(() => { const root = scrollableRef.current ?? document.querySelector<HTMLElement>('.scrollbar-gutter-stable'); if (!root) return; observer.current = typeof IntersectionObserver !== 'undefined' ? new IntersectionObserver(schedule, { root, rootMargin: `${OVERSCAN_PX}px 0px`, threshold: 0 }) : undefined; resize.current = typeof ResizeObserver !== 'undefined' ? new ResizeObserver((entries) => entries.forEach((entry) => { const row = [...rows.current.values()].find((item) => item.element === entry.target); if (row) row.height = entry.borderBoxSize?.[0]?.blockSize ?? entry.contentRect.height; })) : undefined; root.addEventListener('scroll', schedule, { passive: true }); schedule(); return () => { root.removeEventListener('scroll', schedule); observer.current?.disconnect(); resize.current?.disconnect(); if (frame.current != null) cancelAnimationFrame(frame.current); rows.current.clear(); byId.current.clear(); }; }, [conversationId, schedule, scrollableRef]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useMessageWindowing() { const context = useContext(Context); if (!context) throw new Error('useMessageWindowing must be used within MessageWindowingProvider'); return context; }
export function useOptionalMessageWindowing() { return useContext(Context); }
